// AUTO-GENERATED by scripts/gen-module-registry.mjs — do not edit.
// Regenerated before every build and after any helper install/removal.
import type { HelperDefinition } from "./types";
import h0 from "@/helpers/scheduler/helper";

export const INSTALLED_HELPERS: HelperDefinition[] = [h0];
