// AUTO-GENERATED by scripts/gen-module-registry.mjs — do not edit.
// Regenerated before every build and after any helper install/removal.
import type { HelperDefinition } from "./types";

export const INSTALLED_HELPERS: HelperDefinition[] = [];
