"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { setWidgetSizeAction, resetWidgetAction } from "./layout-actions";

/**
 * Wraps a module's dashboard widget with per-user size and position controls.
 *
 * The controls stay out of the way: a small **edit (pencil) icon** in the corner opens a
 * popover holding size and position, instead of the old always-visible "Customise" link and
 * inline panel. Arranging a dashboard is a rare, deliberate act — the dashboard itself
 * should be what you see the rest of the time.
 *
 * Position can be changed two ways, deliberately: **drag the grip** (fast, but no use to a
 * keyboard and unreliable on touch) or the popover's **move buttons** (works everywhere).
 * The grid above owns the drag state; this component only reports the events.
 *
 * The grid span is applied as an inline style, not a Tailwind class — class names built at
 * runtime aren't generated by the JIT compiler and would silently do nothing.
 */
export function WidgetFrame({
  moduleId,
  name,
  width,
  height,
  isFirst,
  isLast,
  dragging,
  dropTarget,
  onDragStartWidget,
  onDragEnterWidget,
  onDragEndWidget,
  onDropWidget,
  onNudge,
  children,
}: {
  moduleId: string;
  name: string;
  width: number;
  height: number;
  isFirst: boolean;
  isLast: boolean;
  dragging: boolean;
  dropTarget: boolean;
  onDragStartWidget: () => void;
  onDragEnterWidget: () => void;
  onDragEndWidget: () => void;
  onDropWidget: () => void;
  onNudge: (direction: "up" | "down") => void;
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(false);
  // `draggable` is armed only while the grip is held. Left always-on it would swallow text
  // selection and interfere with anything interactive inside the widget itself.
  const [armed, setArmed] = useState(false);
  const [pending, startTransition] = useTransition();
  const popoverRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onClick);
    window.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onClick);
      window.removeEventListener("keydown", onKey);
    };
  }, [open]);

  const run = (fn: () => Promise<void>) => startTransition(() => void fn());

  const sizeButton = (active: boolean) =>
    active
      ? { background: "var(--primary)", color: "var(--primary-foreground)" }
      : { border: "1px solid var(--border-strong)" };

  return (
    <div
      className="group relative flex flex-col rounded-xl transition"
      style={{
        gridColumn: `span ${width}`,
        gridRow: `span ${height}`,
        opacity: dragging ? 0.4 : 1,
        outline: dropTarget ? "2px dashed var(--primary)" : undefined,
        outlineOffset: dropTarget ? "4px" : undefined,
      }}
      draggable={armed}
      onDragStart={onDragStartWidget}
      onDragEnter={onDragEnterWidget}
      onDragOver={(e) => e.preventDefault()} // required for a drop to be allowed
      onDrop={(e) => {
        e.preventDefault();
        setArmed(false);
        onDropWidget();
      }}
      onDragEnd={() => {
        setArmed(false);
        onDragEndWidget();
      }}
    >
      <div className="flex-1">{children}</div>

      {/* Controls: subtle until hovered or focused, so the dashboard stays clean. */}
      <div className="pointer-events-none absolute right-2 top-2 flex items-center gap-1 opacity-0 transition group-hover:opacity-100 group-focus-within:opacity-100">
        <span
          className="pointer-events-auto cursor-grab rounded-md p-1 active:cursor-grabbing"
          style={{ background: "var(--surface-2)", color: "var(--muted)" }}
          onMouseDown={() => setArmed(true)}
          onMouseUp={() => setArmed(false)}
          title={`Drag to move the ${name} widget`}
          aria-hidden
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
            <circle cx="9" cy="6" r="1.6" /><circle cx="15" cy="6" r="1.6" />
            <circle cx="9" cy="12" r="1.6" /><circle cx="15" cy="12" r="1.6" />
            <circle cx="9" cy="18" r="1.6" /><circle cx="15" cy="18" r="1.6" />
          </svg>
        </span>

        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          className="pointer-events-auto rounded-md p-1"
          style={{ background: "var(--surface-2)", color: "var(--muted)" }}
          aria-expanded={open}
          aria-label={`Edit the ${name} widget`}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 20h9" />
            <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z" />
          </svg>
        </button>
      </div>

      {open && (
        <div
          ref={popoverRef}
          className="absolute right-2 top-10 z-20 flex w-56 flex-col gap-3 rounded-xl border p-3 text-xs shadow-lg"
          style={{ background: "var(--background)", borderColor: "var(--border)" }}
          role="group"
          aria-label={`${name} widget options`}
        >
          <div className="flex items-center justify-between">
            <span className="font-semibold">{name}</span>
            <button type="button" onClick={() => setOpen(false)} style={{ color: "var(--muted)" }} aria-label="Close">
              ✕
            </button>
          </div>

          <div className="flex items-center justify-between gap-2">
            <span style={{ color: "var(--muted)" }}>Width</span>
            <div className="flex gap-1">
              {[1, 2, 3].map((w) => (
                <button
                  key={w}
                  type="button"
                  disabled={pending}
                  onClick={() => run(() => setWidgetSizeAction(moduleId, w, height))}
                  className="rounded px-2 py-0.5"
                  style={sizeButton(w === width)}
                  aria-pressed={w === width}
                >
                  {w}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center justify-between gap-2">
            <span style={{ color: "var(--muted)" }}>Height</span>
            <div className="flex gap-1">
              {[1, 2, 3].map((h) => (
                <button
                  key={h}
                  type="button"
                  disabled={pending}
                  onClick={() => run(() => setWidgetSizeAction(moduleId, width, h))}
                  className="rounded px-2 py-0.5"
                  style={sizeButton(h === height)}
                  aria-pressed={h === height}
                >
                  {h}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center justify-between gap-2">
            <span style={{ color: "var(--muted)" }}>Position</span>
            <div className="flex gap-1">
              <button
                type="button"
                disabled={isFirst}
                onClick={() => onNudge("up")}
                className="rounded px-2 py-0.5"
                style={{ border: "1px solid var(--border-strong)", opacity: isFirst ? 0.4 : 1 }}
                aria-label="Move this widget earlier"
              >
                ←
              </button>
              <button
                type="button"
                disabled={isLast}
                onClick={() => onNudge("down")}
                className="rounded px-2 py-0.5"
                style={{ border: "1px solid var(--border-strong)", opacity: isLast ? 0.4 : 1 }}
                aria-label="Move this widget later"
              >
                →
              </button>
            </div>
          </div>

          <button
            type="button"
            disabled={pending}
            onClick={() => run(() => resetWidgetAction(moduleId))}
            className="self-start"
            style={{ color: "var(--muted)" }}
          >
            Reset to default
          </button>
        </div>
      )}
    </div>
  );
}
