"use client";

import { useState, useTransition } from "react";
import { setWidgetSizeAction, moveWidgetAction, resetWidgetAction } from "./layout-actions";

/**
 * Wraps a module's dashboard widget with per-user size and position controls.
 *
 * Deliberately explicit buttons rather than drag-and-drop: dragging needs a sizeable
 * dependency, is fiddly on touch, and is close to unusable with a keyboard or screen
 * reader. Widening/reordering is a rare, deliberate act, so a discreet "Customise"
 * toggle keeps the dashboard clean while staying fully accessible.
 *
 * The grid span is applied as an inline style, not a Tailwind class — class names built
 * at runtime aren't generated by the JIT compiler and would silently do nothing.
 */
export function WidgetFrame({
  moduleId,
  name,
  width,
  height,
  orderedIds,
  children,
}: {
  moduleId: string;
  name: string;
  width: number;
  height: number;
  orderedIds: string[];
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();

  const index = orderedIds.indexOf(moduleId);
  const canMoveUp = index > 0;
  const canMoveDown = index >= 0 && index < orderedIds.length - 1;

  const run = (fn: () => Promise<void>) => startTransition(() => void fn());

  return (
    <div
      className="relative flex flex-col"
      style={{
        // Span on wider screens only; a phone keeps every widget full width.
        gridColumn: `span ${width}`,
        gridRow: `span ${height}`,
      }}
    >
      <div className="flex-1">{children}</div>

      <div className="mt-1 flex justify-end">
        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          className="text-xs"
          style={{ color: "var(--muted)" }}
          aria-expanded={open}
          aria-label={`Customise the ${name} widget`}
        >
          {open ? "Done" : "Customise"}
        </button>
      </div>

      {open && (
        <div className="mt-1 flex flex-wrap items-center gap-3 rounded-lg p-2 text-xs" style={{ background: "var(--surface-2)" }}>
          <span style={{ color: "var(--muted)" }}>Width</span>
          <div className="flex gap-1">
            {[1, 2, 3].map((w) => (
              <button
                key={w}
                type="button"
                disabled={pending}
                onClick={() => run(() => setWidgetSizeAction(moduleId, w, height))}
                className="rounded px-2 py-0.5"
                style={
                  w === width
                    ? { background: "var(--primary)", color: "white" }
                    : { border: "1px solid var(--border-strong)" }
                }
                aria-pressed={w === width}
              >
                {w}
              </button>
            ))}
          </div>

          <span style={{ color: "var(--muted)" }}>Height</span>
          <div className="flex gap-1">
            {[1, 2, 3].map((h) => (
              <button
                key={h}
                type="button"
                disabled={pending}
                onClick={() => run(() => setWidgetSizeAction(moduleId, width, h))}
                className="rounded px-2 py-0.5"
                style={
                  h === height
                    ? { background: "var(--primary)", color: "white" }
                    : { border: "1px solid var(--border-strong)" }
                }
                aria-pressed={h === height}
              >
                {h}
              </button>
            ))}
          </div>

          <div className="flex gap-1">
            <button
              type="button"
              disabled={pending || !canMoveUp}
              onClick={() => run(() => moveWidgetAction(moduleId, "up", orderedIds))}
              className="rounded px-2 py-0.5"
              style={{ border: "1px solid var(--border-strong)", opacity: canMoveUp ? 1 : 0.4 }}
              aria-label="Move this widget earlier"
            >
              ←
            </button>
            <button
              type="button"
              disabled={pending || !canMoveDown}
              onClick={() => run(() => moveWidgetAction(moduleId, "down", orderedIds))}
              className="rounded px-2 py-0.5"
              style={{ border: "1px solid var(--border-strong)", opacity: canMoveDown ? 1 : 0.4 }}
              aria-label="Move this widget later"
            >
              →
            </button>
          </div>

          <button
            type="button"
            disabled={pending}
            onClick={() => run(() => resetWidgetAction(moduleId))}
            style={{ color: "var(--muted)" }}
          >
            Reset
          </button>
        </div>
      )}
    </div>
  );
}
