// AUTO-GENERATED by scripts/gen-module-registry.mjs — do not edit.
// Regenerated before every build and after any module install/uninstall.
import type { ModuleDefinition } from "./types";

export const INSTALLED: ModuleDefinition[] = [];
